keys:
 - &primary age193nsc6nktm9kvklsdjjqq2dvrurhwzw9e2arty4svudn88wllggsurnexs
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
        - age:
          - *primary