# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  networking.hostId = "ad53f8bc";
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/9ade4de4-cf0f-4852-8855-827d6034aa3a";
      fsType = "ext4";
    };
    "/boot" = {
      device = "UUID=67C9-9661";
      fsType = "vfat";
    };
    "/drives/128GSSD" = {
      device = "/dev/disk/by-uuid/97ba97b1-f9c5-4ec2-8b2f-8eaaf8c20329";
      fsType = "ext4";
    };
    "'/drives/500GHDD" = {
      device = "/dev/disk/by-uuid/3e2b804b-8521-4433-97aa-5d70560802a0";
      fsType = "ext4";
    };
    "/drives/500GSSD" = {
      device = "/dev/disk/by-uuid/ebe6c0b5-2383-4c07-bc9d-184e8e669754";
      fsType = "ext4";
    };
    "/drives/2TBHDD" = {
      device = "/dev/disk/by-uuid/cd25a73a-5694-4895-af7d-f7bf2facc081";
      fsType = "ext4";
    };

    "/uWebServer" = {
      device = "krutonium@krutonium.ca:/";
      fsType = "sshfs";
      options = [
        "allow_other" # for non-root access
        "default_permissions"
        "idmap=user"
        "_netdev" # requires network to mount
        "x-systemd.automount" # mount on demand
        "uid=1002" # id -a
        "gid=100"
        "max_conns=20" # MOAR THREADS (when needed)
        "IdentityFile=/home/krutonium/.ssh/id_ed25519"
        # Handle connection drops better
        "ServerAliveInterval=2"
        "ServerAliveCountMax=2"
        "reconnect"
        "x-gvfs-show"
        "x-gvfs-name=uWebServer"
      ];
    };
    "/uServerHost" = {
      device = "root@10.3:/";
      fsType = "sshfs";
      options = [
        "allow_other" # for non-root access
        "default_permissions"
        "idmap=user"
        "_netdev" # requires network to mount
        "x-systemd.automount" # mount on demand
        "uid=1002" # id -a
        "gid=100"
        "max_conns=20" # MOAR THREADS (when needed)
        "IdentityFile=/home/krutonium/.ssh/id_ed25519"
        # Handle connection drops better
        "ServerAliveInterval=2"
        "ServerAliveCountMax=2"
        "reconnect"
        "x-gvfs-show"
        "x-gvfs-name=uServerHost"
      ];
    };
  };
  swapDevices = [ ];
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
