# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  networking.hostId = "ad53f8bc";
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e918ba08-3692-42a9-b53a-ee6d04877088";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/6E00-6801";
      fsType = "vfat";
    };
  fileSystems."/games/SSD" =
    {
      device = "/dev/disk/by-uuid/5c1a2a62-f86a-42a6-b980-d7b08faca798";
      fsType = "ext4";
    };
  fileSystems."/games/500G" = 
    {
      device = "/dev/disk/by-uuid/fcac9ff4-d9d9-4d95-98e0-41c903923dbf";
      fsType = "ext4";
    };
  fileSystems."/games/2TB" = 
    {
      device = "/dev/disk/by-uuid/9dc02eac-67cb-46b2-9332-dfecdf50e4a2";
      fsType = "ext4";
    };

  boot.zfs.extraPools = [ "Games" ];
  swapDevices = [ ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
