# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  system.fsPackages = [ pkgs.sshfs ];
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/a387c76d-cc06-435a-8278-f81fba61e0e4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0CBA-0C11";
      fsType = "vfat";
    };

  fileSystems."/home/krutonium/steam" =
    {
      device = "/dev/disk/by-uuid/4d4d93e3-8b59-45b2-b29a-53759dcc9dd4";
      fsType = "ext4";
    };
  fileSystems."/uWebServer" =
    {
      device = "krutonium@krutonium.ca:/";
      #mountPoint = "";
      fsType = "sshfs";
      options =
        [ "allow_other"          # for non-root access
          "default_permissions"
          "idmap=user"
          "_netdev"              # requires network to mount
          "x-systemd.automount"  # mount on demand
          "uid=1000"
          "gid=100"
          # The ssh key must not be encrypted, have strict
          # permissions (like 600) and owned by root.
          "IdentityFile=/home/krutonium/.ssh/id_ed25519"
          
          # Handle connection drops better
          "ServerAliveInterval=15"
          "reconnect"
          # Uncomment this if you're having a hard time
          # figuring why mounting is failing.
          #"debug"
        ];
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
